import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";

// https://nextjs.org/docs/app/building-your-application/routing/layouts-and-templates#root-layout-required

const inter = Inter({ subsets: ["latin"] });

// Golbal metadata
export const metadata: Metadata = {
  title: {
    default: "Explore NextJs",
    template: "%s | Explore NextJs",
    // absolute: "hehe Explore NextJs", // read this
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <Sidebar />

          <div className="border border-pink-400 p-4 m-4 w-full">
            <h2 className="font-bold text-pink-400">Root Layouts</h2>
            <div className="mb-4">This layout is in the root app folder</div>
            <h3 className="font-bold mb-2 text-pink-400">Content</h3>
            <div className="border border-pink-400 border-dashed p-4">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
